name: Dependabot Auto-Merge
description: Automatically approve and merge Dependabot PRs based on configurable rules

inputs:
  config:
    description: "JSON array of merge rules"
    required: true
  github-token:
    description: "GitHub token with pull-request write permissions"
    required: true
  merge-method:
    description: "Merge method (squash, merge, rebase)"
    default: "squash"

runs:
  using: composite
  steps:
    - name: Dependabot metadata
      id: meta
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ inputs.github-token }}

    - name: Check if auto-merge applicable
      id: check
      uses: actions/github-script@v8
      env:
        AUTO_MERGE_CONFIG: ${{ inputs.config }}
        DEP_NAMES: ${{ steps.meta.outputs.dependency-names }}
        PACKAGE_ECOSYSTEM: ${{ steps.meta.outputs.package-ecosystem }}
        UPDATE_TYPE: ${{ steps.meta.outputs.update-type }}
      with:
        script: |
          const { checkAutoMerge } = require('${{ github.action_path }}/check-auto-merge');

          // Strip trailing commas
          const configJson = process.env.AUTO_MERGE_CONFIG.replace(/,\s*([}\]])/g, '$1');

          const result = checkAutoMerge({
            config: JSON.parse(configJson),
            dependencyNames: process.env.DEP_NAMES.split(/,\s*/),
            packageEcosystem: process.env.PACKAGE_ECOSYSTEM,
            updateType: process.env.UPDATE_TYPE,
          });
          console.log(`Result: ${JSON.stringify(result)}`);
          core.setOutput('should_merge', result.shouldMerge ? 'true' : 'false');

    - name: Approve dependabot PR
      if: steps.check.outputs.should_merge == 'true'
      run: gh pr review --approve "$PR_URL"
      shell: bash
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Enable auto-merge
      if: steps.check.outputs.should_merge == 'true'
      run: gh pr merge --auto --${{ inputs.merge-method }} "$PR_URL"
      shell: bash
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ inputs.github-token }}
